-- Bài tập cơ bản
-- 1. Top 10 đơn hàng lớn nhất kèm tên KH
SELECT 
	O.ORDER_NUMBER, 
	O.ORDER_DATE, 
	C.CUSTOMER_NAME, 
	O.TOTAL_AMOUNT
FROM ORDERS O
JOIN CUSTOMER C
USING (CUSTOMER_ID)
ORDER BY O.TOTAL_AMOUNT DESC
LIMIT 10;

-- 2. Doanh thu theo kênh đăng ký của KH
SELECT
	C.SIGNUP_SOURCE,
	SUM(O.TOTAL_AMOUNT) AS TOTAL_SALES
FROM CUSTOMER C
JOIN ORDERS O
USING (CUSTOMER_ID)
GROUP BY C.SIGNUP_SOURCE

-- 3. KH không có đơn trong 30 ngày gần đây
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME
FROM CUSTOMER C
LEFT JOIN ORDERS O
	ON C.CUSTOMER_ID = O.CUSTOMER_ID AND O.ORDER_DATE >= CURRENT_DATE - 30
WHERE O.ID IS NULL;

-- 4. So sánh điều kiện ON vs WHERE với Gmail
SELECT COUNT(*) FROM ORDERS O
RIGHT JOIN CUSTOMER C ON C.CUSTOMER_ID = O.CUSTOMER_ID AND C.EMAIL ILIKE '%gmail%';

SELECT COUNT(*) FROM ORDERS O
RIGHT JOIN CUSTOMER C
USING (CUSTOMER_ID)
WHERE C.EMAIL ILIKE '%gmail%';

-- Bài tập mở rộng
-- Bài 1
SELECT 
	C.CUSTOMER_ID, 
	C.CUSTOMER_NAME, 
	C.EMAIL,
	AVG(O.TOTAL_AMOUNT) AS AVG_TOTAL_AMOUNT
FROM CUSTOMER C
INNER JOIN ORDERS O
USING (CUSTOMER_ID)
WHERE C.EMAIL ILIKE '%@gmail%'
GROUP BY C.CUSTOMER_ID;

-- 2. Số đơn 30 ngày gần đây theo trạng thái
SELECT
	O.STATUS,
	COUNT(*) AS SO_DON_HANG
FROM CUSTOMER C
JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_DATE >= CURRENT_DATE - 30
GROUP BY O.STATUS;

-- 3. Ngày đặt hàng gần nhất của mỗi KH
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    MAX(O.ORDER_DATE) AS LAST_ORDER_DATE
FROM CUSTOMER C
LEFT JOIN ORDERS O
USING (CUSTOMER_ID)
GROUP BY C.CUSTOMER_ID
ORDER BY LAST_ORDER_DATE DESC;

-- 4. KH chưa từng có đơn DELIVERED
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME
FROM CUSTOMER C
LEFT JOIN ORDERS O
ON O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'DELIVERED'
WHERE O.STATUS IS NULL
GROUP BY C.CUSTOMER_ID;

-- 5. Số đơn của KH VIP GOLD theo kênh
SELECT COUNT(*), O.CHANNEL
FROM ORDERS AS O 
LEFT JOIN CUSTOMER AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID 
WHERE C.VIP_TIER='GOLD'
GROUP BY O.CHANNEL;

-- 6. Đếm số đơn theo vip_tier (giữ cả tier không có đơn)
SELECT
	C.VIP_TIER,
	COUNT(*) AS SO_DON_HANG
FROM CUSTOMER C
RIGHT JOIN ORDERS O
USING (CUSTOMER_ID)
GROUP BY C.VIP_TIER;

-- 7. Khách hàng không hoạt động nhưng vẫn có đơn
SELECT DISTINCT
       c.customer_id,
       c.customer_name
FROM orders o
RIGHT JOIN customer c
USING (customer_id)
WHERE c.is_active = false
  AND o.id IS NOT NULL
