CREATE TABLESPACE demo_tz
OWNER postgres
LOCATION '/home/demo_tz';

CREATE SCHEMA IF NOT EXISTS DEMO;
SET SEARCH_PATH TO DEMO, PUBLIC;

SHOW SEARCH_PATH;

-- =========================	
-- 1. TẠO BẢNG
-- =========================
CREATE TABLE HOC_VIEN (
    ID SERIAL PRIMARY KEY,
    HO_TEN VARCHAR
) TABLESPACE DEMO_TZ;

CREATE TABLE GIAO_VIEN (
    ID SERIAL PRIMARY KEY,
    HO_TEN VARCHAR(150) NOT NULL
) TABLESPACE DEMO_TZ;

CREATE TABLE KHOA_HOC (
    ID SERIAL PRIMARY KEY,
    TEN VARCHAR
) TABLESPACE DEMO_TZ;

CREATE TABLE LOP_HOC (
    ID SERIAL PRIMARY KEY,
    TEN VARCHAR,
    KHOA_HOC_ID INT NOT NULL REFERENCES KHOA_HOC(ID),
    GIAO_VIEN_ID INT NOT NULL REFERENCES GIAO_VIEN(ID),
    CONSTRAINT UQ_LOP_KHOA UNIQUE (ID, KHOA_HOC_ID)
) TABLESPACE DEMO_TZ;

CREATE TABLE DANG_KY_HOC (
    HOC_VIEN_ID INT NOT NULL REFERENCES HOC_VIEN(ID),
    KHOA_HOC_ID INT NOT NULL REFERENCES KHOA_HOC(ID),
    LOP_HOC_ID INT NULL,
    NGAY_DANG_KY DATE,
    TRANG_THAI VARCHAR,
    CONSTRAINT UQ_HV_LOP UNIQUE (HOC_VIEN_ID, LOP_HOC_ID),
    CONSTRAINT UQ_HV_KH UNIQUE (HOC_VIEN_ID, KHOA_HOC_ID),
    CONSTRAINT FK_DANGKY_LOP_KHOA FOREIGN KEY (LOP_HOC_ID, KHOA_HOC_ID)
        REFERENCES LOP_HOC(ID, KHOA_HOC_ID)
) TABLESPACE DEMO_TZ;

-- =========================
-- 2. SEED DỮ LIỆU
-- =========================
BEGIN;

-- RESET DỮ LIỆU
TRUNCATE TABLE DANG_KY_HOC, LOP_HOC, HOC_VIEN, GIAO_VIEN, KHOA_HOC
RESTART IDENTITY CASCADE;

-- 1) 100 KHÓA HỌC
INSERT INTO DEMO.KHOA_HOC (TEN)
SELECT 'KHOA ' || I
FROM GENERATE_SERIES(1, 100) AS G(I);

-- 2) 5000 GIÁO VIÊN
INSERT INTO DEMO.GIAO_VIEN (HO_TEN)
SELECT 'GIAO VIEN ' || I
FROM GENERATE_SERIES(1, 5000) AS G(I);

-- 3) 20K LỚP HỌC: MỖI KHÓA 200 LỚP
INSERT INTO DEMO.LOP_HOC (TEN, KHOA_HOC_ID, GIAO_VIEN_ID)
SELECT 'LOP KH' || KH || '-' || N,
       KH,
       ((KH*200 + N) % 5000) + 1
FROM GENERATE_SERIES(1, 100) AS KH
CROSS JOIN GENERATE_SERIES(1, 200) AS N;

-- 4) 1 TRIỆU HỌC VIÊN
INSERT INTO DEMO.HOC_VIEN (HO_TEN)
SELECT 'HOC VIEN ' || I
FROM GENERATE_SERIES(1, 1000000) AS G(I);

-- 5) TẠO ĐĂNG KÝ HỌC NGẪU NHIÊN
WITH LOP_MAP AS (
    SELECT KHOA_HOC_ID, ARRAY_AGG(ID) AS LOP_IDS
    FROM DEMO.LOP_HOC
    GROUP BY KHOA_HOC_ID
)
INSERT INTO DEMO.DANG_KY_HOC(HOC_VIEN_ID, KHOA_HOC_ID, LOP_HOC_ID, NGAY_DANG_KY, TRANG_THAI)
SELECT 
    HV.ID,
    1 + (ABS(HASHTEXTEXTENDED(HV.ID::TEXT, 0)) % 100) AS KH_ID,
    CASE WHEN RANDOM() < 0.25 THEN NULL
         ELSE (
            (SELECT LOP_IDS[1 + FLOOR(RANDOM()*ARRAY_LENGTH(LOP_IDS,1))::INT]
             FROM LOP_MAP LM 
             WHERE LM.KHOA_HOC_ID = 1 + (ABS(HASHTEXTEXTENDED(HV.ID::TEXT, 0)) % 100))
         )
    END,
    DATE '2024-01-01' + (FLOOR(RANDOM()*600)::INT),
    (ARRAY['ACTIVE','CANCELLED','COMPLETED','ON_HOLD'])[1 + FLOOR(RANDOM()*4)::INT]
FROM DEMO.HOC_VIEN HV;

COMMIT;

-- =========================
-- 3. INDEXES & OPTIMIZATIONS
-- =========================

-- TÌM LỚP THEO KHÓA HỌC
CREATE INDEX IDX_LOPHOC_KHOAHOC ON LOP_HOC(KHOA_HOC_ID);

-- TRA CỨU ĐĂNG KÝ HỌC VIÊN
CREATE INDEX IDX_DANGKYHOC_HV_NGAY_INCLUDE 
ON DANG_KY_HOC(HOC_VIEN_ID, NGAY_DANG_KY DESC)
INCLUDE (TRANG_THAI);

-- BÁO CÁO SỐ LƯỢNG HỌC VIÊN / KHÓA
CREATE INDEX IDX_DANGKYHOC_KHOAHOC ON DANG_KY_HOC(KHOA_HOC_ID);

CREATE MATERIALIZED VIEW MV_HOCVIEN_KHOAHOC AS
SELECT KHOA_HOC_ID, COUNT(*) AS SO_LUONG
FROM DANG_KY_HOC
GROUP BY KHOA_HOC_ID;

REFRESH MATERIALIZED VIEW MV_HOCVIEN_KHOAHOC;


-- TRA CỨU THÔNG TIN THEO LỚP HỌC
CREATE INDEX IDX_DANGKYHOC_LOPHOC ON DANG_KY_HOC(LOP_HOC_ID);

-- ĐẾM ĐĂNG KÝ THEO KHÓA HỌC & TRẠNG THÁI
CREATE INDEX IDX_DANGKYHOC_KHOAHOC_TRANGTHAI 
ON DANG_KY_HOC(KHOA_HOC_ID, TRANG_THAI);

-- LIỆT KÊ LỚP THEO KHÓA HỌC
CREATE INDEX IDX_LOPHOC_KHOAHOC ON LOP_HOC(KHOA_HOC_ID);

-- LỊCH SỬ ĐĂNG KÝ HỌC VIÊN
CREATE INDEX IDX_DANGKYHOC_HOCVIEN_NGAYDANGKY 
ON DANG_KY_HOC(HOC_VIEN_ID, NGAY_DANG_KY DESC);
