-- BÀI TẬP PARTITION
-- C4. HÃY TẠO PARENT THEO NĂM (RANGE) RỒI SUB-PARTITION THEO CỘT CHANNEL (LIST PARTITION)
DROP TABLE IF EXISTS ORDERS_P_RANGE;

-- TẠO PARTITION CHA
CREATE TABLE ORDERS_P_RANGE (
	ID 				SERIAL,	
	ORDER_NUMBER 	TEXT 			NOT NULL,
	CUSTOMER_ID 	INT 			NOT NULL,
	ORDER_DATE 		DATE 			NOT NULL,
	STATUS 			TEXT 			NOT NULL CHECK (STATUS IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED')),
	PAYMENT_METHOD 	TEXT 			NOT NULL CHECK (PAYMENT_METHOD IN ('CARD', 'CASH', 'EWALLET', 'BANK_TRANSFER')),
	SHIPPING_METHOD TEXT 			NOT NULL CHECK (SHIPPING_METHOD IN ('STANDARD', 'EXPRESS', 'PICKUP')),
	CHANNEL 		TEXT 			NOT NULL CHECK (CHANNEL IN ('web', 'mobile', 'store', 'partner')),
	CURRENCY 		CHAR(3) 		NOT NULL DEFAULT 'USD',
	COUPON_CODE 	TEXT,	
	SUBTOTAL_AMOUNT NUMERIC(10, 2) 	NOT NULL,
	DISCOUNT_AMOUNT NUMERIC(10, 2) 	NOT NULL DEFAULT 0,
	TAX_AMOUNT 		NUMERIC(10, 2) 	NOT NULL DEFAULT 0,
	SHIPPING_FEE 	NUMERIC(10, 2) 	NOT NULL DEFAULT 0,
	TOTAL_AMOUNT 	NUMERIC(10, 2) 	NOT NULL CHECK (TOTAL_AMOUNT >= 0),
	CREATED_AT 		TIMESTAMPTZ 	NOT NULL DEFAULT NOW(),
	UPDATED_AT 		TIMESTAMPTZ 	NOT NULL DEFAULT NOW(),
	CONSTRAINT PK_ORDERS_P_RANGE PRIMARY KEY (ID, ORDER_DATE, CHANNEL),
	CONSTRAINT UQ_ORDERS_P_RANGE_ORDER_NUMBER UNIQUE (ORDER_NUMBER, ORDER_DATE, CHANNEL),
	CONSTRAINT FK_ORDERS_P_RANGE_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
)
PARTITION BY RANGE (ORDER_DATE);

-- PARTITION CHO 2024
CREATE TABLE ORDERS_P_2024 PARTITION OF ORDERS_P_RANGE
FOR VALUES FROM ('2024-01-01') TO ('2024-12-31')
PARTITION BY LIST (CHANNEL);

-- PARTITION CHO 2025
CREATE TABLE ORDERS_P_2025 PARTITION OF ORDERS_P_RANGE
FOR VALUES FROM ('2025-01-01') TO ('2025-12-31')
PARTITION BY LIST (CHANNEL);

-- PARTITION MẶC ĐỊNH CHO DỮ LIỆU NGOÀI KHOẢNG
CREATE TABLE ORDERS_P_DEFAULT PARTITION OF ORDERS_P_RANGE DEFAULT
PARTITION BY LIST (CHANNEL);

-- SUB-PARTITIONS THEO CHANNEL CHO TỪNG NĂM
-- 2024
CREATE TABLE ORDERS_2024_WEB     PARTITION OF ORDERS_P_2024 FOR VALUES IN ('web');
CREATE TABLE ORDERS_2024_MOBILE  PARTITION OF ORDERS_P_2024 FOR VALUES IN ('mobile');
CREATE TABLE ORDERS_2024_STORE   PARTITION OF ORDERS_P_2024 FOR VALUES IN ('store');
CREATE TABLE ORDERS_2024_PARTNER PARTITION OF ORDERS_P_2024 FOR VALUES IN ('partner');

-- 2025
CREATE TABLE ORDERS_2025_WEB     PARTITION OF ORDERS_P_2025 FOR VALUES IN ('web');
CREATE TABLE ORDERS_2025_MOBILE  PARTITION OF ORDERS_P_2025 FOR VALUES IN ('mobile');
CREATE TABLE ORDERS_2025_STORE   PARTITION OF ORDERS_P_2025 FOR VALUES IN ('store');
CREATE TABLE ORDERS_2025_PARTNER PARTITION OF ORDERS_P_2025 FOR VALUES IN ('partner');

-- default
CREATE TABLE ORDERS_DEFAULT_WEB     PARTITION OF ORDERS_P_DEFAULT FOR VALUES IN ('web');
CREATE TABLE ORDERS_DEFAULT_MOBILE  PARTITION OF ORDERS_P_DEFAULT FOR VALUES IN ('mobile');
CREATE TABLE ORDERS_DEFAULT_STORE   PARTITION OF ORDERS_P_DEFAULT FOR VALUES IN ('store');
CREATE TABLE ORDERS_DEFAULT_PARTNER PARTITION OF ORDERS_P_DEFAULT FOR VALUES IN ('partner');

-- THÊM DỮ LIỆU TỪ BẢNG ORDERS CŨ
INSERT INTO ORDERS_P_RANGE (
	ID, ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, STATUS, PAYMENT_METHOD, SHIPPING_METHOD,
	CHANNEL, CURRENCY, COUPON_CODE, SUBTOTAL_AMOUNT, DISCOUNT_AMOUNT, TAX_AMOUNT,
	SHIPPING_FEE, TOTAL_AMOUNT, CREATED_AT, UPDATED_AT
)
SELECT
	ID, ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, STATUS, PAYMENT_METHOD, SHIPPING_METHOD,
	CHANNEL, CURRENCY, COUPON_CODE, SUBTOTAL_AMOUNT, DISCOUNT_AMOUNT, TAX_AMOUNT,
	SHIPPING_FEE, TOTAL_AMOUNT, CREATED_AT, UPDATED_AT
FROM ORDERS
WHERE ORDER_DATE >= '2024-01-01';

EXPLAIN ANALYZE
SELECT COUNT(*)
FROM ORDERS_P_RANGE
WHERE ORDER_DATE >= '2024-01-01' AND ORDER_DATE < '2024-12-31' AND CHANNEL = 'web';


-- C5. Hãy tạo parent theo năm (RANGE) rồi sub-partition theo customer_id (HASH partition với 8 phần)
CREATE TABLE ORDERS_P_RANGE_HASH (
	ID 				SERIAL,	
	ORDER_NUMBER 	TEXT 			NOT NULL,
	CUSTOMER_ID 	INT 			NOT NULL,
	ORDER_DATE 		DATE 			NOT NULL,
	STATUS 			TEXT 			NOT NULL CHECK (STATUS IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED')),
	PAYMENT_METHOD 	TEXT 			NOT NULL CHECK (PAYMENT_METHOD IN ('CARD', 'CASH', 'EWALLET', 'BANK_TRANSFER')),
	SHIPPING_METHOD TEXT 			NOT NULL CHECK (SHIPPING_METHOD IN ('STANDARD', 'EXPRESS', 'PICKUP')),
	CHANNEL 		TEXT 			NOT NULL CHECK (CHANNEL IN ('web', 'mobile', 'store', 'partner')),
	CURRENCY 		CHAR(3) 		NOT NULL DEFAULT 'USD',
	COUPON_CODE 	TEXT,	
	SUBTOTAL_AMOUNT NUMERIC(10, 2) 	NOT NULL,
	DISCOUNT_AMOUNT NUMERIC(10, 2) 	NOT NULL DEFAULT 0,
	TAX_AMOUNT 		NUMERIC(10, 2) 	NOT NULL DEFAULT 0,
	SHIPPING_FEE 	NUMERIC(10, 2) 	NOT NULL DEFAULT 0,
	TOTAL_AMOUNT 	NUMERIC(10, 2) 	NOT NULL CHECK (TOTAL_AMOUNT >= 0),
	CREATED_AT 		TIMESTAMPTZ 	NOT NULL DEFAULT NOW(),
	UPDATED_AT 		TIMESTAMPTZ 	NOT NULL DEFAULT NOW(),
	CONSTRAINT PK_ORDERS_P_RANGE_HASH PRIMARY KEY (ID, ORDER_DATE, CUSTOMER_ID),
	CONSTRAINT UQ_ORDERS_P_RANGE_HASH_ORDER_NUMBER UNIQUE (ORDER_NUMBER, ORDER_DATE, CUSTOMER_ID),
	CONSTRAINT FK_ORDERS_P_RANGE_HASH_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
)
PARTITION BY RANGE (ORDER_DATE);

-- PARTITION CHO 2024
CREATE TABLE ORDERS_HASH_2024 PARTITION OF ORDERS_P_RANGE_HASH
FOR VALUES FROM ('2024-01-01') TO ('2024-12-31')
PARTITION BY HASH (CUSTOMER_ID);

-- PARTITION CHO 2025
CREATE TABLE ORDERS_HASH_2025 PARTITION OF ORDERS_P_RANGE_HASH
FOR VALUES FROM ('2025-01-01') TO ('2025-12-31')
PARTITION BY HASH (CUSTOMER_ID);

-- PARTITION MẶC ĐỊNH CHO DỮ LIỆU NGOÀI KHOẢNG
CREATE TABLE ORDERS_HASH_DEFAULT PARTITION OF ORDERS_P_RANGE_HASH DEFAULT
PARTITION BY HASH (CUSTOMER_ID);

-- SUB-PARTITIONS HASH THEO CUSTOMER_ID
-- 2024
CREATE TABLE ORDERS_2024_H0 PARTITION OF ORDERS_HASH_2024 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE ORDERS_2024_H1 PARTITION OF ORDERS_HASH_2024 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE ORDERS_2024_H2 PARTITION OF ORDERS_HASH_2024 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE ORDERS_2024_H3 PARTITION OF ORDERS_HASH_2024 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE ORDERS_2024_H4 PARTITION OF ORDERS_HASH_2024 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE ORDERS_2024_H5 PARTITION OF ORDERS_HASH_2024 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE ORDERS_2024_H6 PARTITION OF ORDERS_HASH_2024 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE ORDERS_2024_H7 PARTITION OF ORDERS_HASH_2024 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

-- 2025
CREATE TABLE ORDERS_2025_H0 PARTITION OF ORDERS_HASH_2025 FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE ORDERS_2025_H1 PARTITION OF ORDERS_HASH_2025 FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE ORDERS_2025_H2 PARTITION OF ORDERS_HASH_2025 FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE ORDERS_2025_H3 PARTITION OF ORDERS_HASH_2025 FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE ORDERS_2025_H4 PARTITION OF ORDERS_HASH_2025 FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE ORDERS_2025_H5 PARTITION OF ORDERS_HASH_2025 FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE ORDERS_2025_H6 PARTITION OF ORDERS_HASH_2025 FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE ORDERS_2025_H7 PARTITION OF ORDERS_HASH_2025 FOR VALUES WITH (MODULUS 8, REMAINDER 7);

-- default
CREATE TABLE ORDERS_DEFAULT_H0 PARTITION OF ORDERS_HASH_DEFAULT FOR VALUES WITH (MODULUS 8, REMAINDER 0);
CREATE TABLE ORDERS_DEFAULT_H1 PARTITION OF ORDERS_HASH_DEFAULT FOR VALUES WITH (MODULUS 8, REMAINDER 1);
CREATE TABLE ORDERS_DEFAULT_H2 PARTITION OF ORDERS_HASH_DEFAULT FOR VALUES WITH (MODULUS 8, REMAINDER 2);
CREATE TABLE ORDERS_DEFAULT_H3 PARTITION OF ORDERS_HASH_DEFAULT FOR VALUES WITH (MODULUS 8, REMAINDER 3);
CREATE TABLE ORDERS_DEFAULT_H4 PARTITION OF ORDERS_HASH_DEFAULT FOR VALUES WITH (MODULUS 8, REMAINDER 4);
CREATE TABLE ORDERS_DEFAULT_H5 PARTITION OF ORDERS_HASH_DEFAULT FOR VALUES WITH (MODULUS 8, REMAINDER 5);
CREATE TABLE ORDERS_DEFAULT_H6 PARTITION OF ORDERS_HASH_DEFAULT FOR VALUES WITH (MODULUS 8, REMAINDER 6);
CREATE TABLE ORDERS_DEFAULT_H7 PARTITION OF ORDERS_HASH_DEFAULT FOR VALUES WITH (MODULUS 8, REMAINDER 7);

-- THÊM DỮ LIỆU TỪ BẢNG ORDERS CŨ
INSERT INTO ORDERS_P_RANGE_HASH (
	ID, ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, STATUS, PAYMENT_METHOD, SHIPPING_METHOD,
	CHANNEL, CURRENCY, COUPON_CODE, SUBTOTAL_AMOUNT, DISCOUNT_AMOUNT, TAX_AMOUNT,
	SHIPPING_FEE, TOTAL_AMOUNT, CREATED_AT, UPDATED_AT
)
SELECT
	ID, ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, STATUS, PAYMENT_METHOD, SHIPPING_METHOD,
	CHANNEL, CURRENCY, COUPON_CODE, SUBTOTAL_AMOUNT, DISCOUNT_AMOUNT, TAX_AMOUNT,
	SHIPPING_FEE, TOTAL_AMOUNT, CREATED_AT, UPDATED_AT
FROM ORDERS
WHERE ORDER_DATE >= '2024-01-01';

EXPLAIN ANALYZE
SELECT COUNT(*)
FROM ORDERS_P_RANGE_HASH
WHERE ORDER_DATE >= '2024-01-01' AND ORDER_DATE < '2024-12-31' AND (CUSTOMER_ID BETWEEN 50 AND 1000);


-- Bài tập buổi 7
CREATE TABLESPACE demo_tz
OWNER postgres
LOCATION '/home/demo_tz';

CREATE SCHEMA IF NOT EXISTS demo;

SET search_path to demo, public;

-- HỌC VIÊN
DROP TABLE IF EXISTS HOC_VIEN CASCADE;
CREATE TABLE HOC_VIEN (
	MA_SV        SERIAL 		PRIMARY KEY,
	HO_TEN       VARCHAR(150) 	NOT NULL,
	NGAY_SINH    DATE        	NOT NULL,
	SDT          VARCHAR(20)  	NOT NULL,
	EMAIL        VARCHAR(254)	NOT NULL,
	CREATED_AT   TIMESTAMPTZ  	NOT NULL DEFAULT NOW(),
	UPDATED_AT   TIMESTAMPTZ  	NOT NULL DEFAULT NOW(),
	CONSTRAINT UQ_HV_EMAIL 	UNIQUE (EMAIL),
	CONSTRAINT UQ_HV_SDT   	UNIQUE (SDT)
) TABLESPACE DEMO_TZ;

-- GIÁO VIÊN
DROP TABLE IF EXISTS GIAO_VIEN CASCADE;
CREATE TABLE GIAO_VIEN (
	MA_GV        SERIAL 		PRIMARY KEY,
	HO_TEN       VARCHAR(150) 	NOT NULL,
	CHUYEN_MON   VARCHAR(150) 	NOT NULL,
	SDT          VARCHAR(20)  	NOT NULL,
	EMAIL        VARCHAR(254) 	NOT NULL,
	CREATED_AT   TIMESTAMPTZ  	NOT NULL DEFAULT NOW(),
	UPDATED_AT   TIMESTAMPTZ  	NOT NULL DEFAULT NOW(),
	CONSTRAINT UQ_GV_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_GV_SDT   UNIQUE (SDT)
) TABLESPACE DEMO_TZ;

-- KHÓA HỌC
DROP TABLE IF EXISTS KHOA_HOC CASCADE;
CREATE TABLE KHOA_HOC (
	MA_KHOA_HOC   	SERIAL			PRIMARY KEY,
	TEN_KHOA_HOC  	VARCHAR(200) 	NOT NULL,
	THOI_LUONG_GIO	SMALLINT    	NOT NULL CHECK (THOI_LUONG_GIO > 0),
	HOC_PHI       	INTEGER      	NOT NULL CHECK (HOC_PHI >= 0),
	CREATED_AT    	TIMESTAMPTZ  	NOT NULL DEFAULT NOW(),
	UPDATED_AT    	TIMESTAMPTZ  	NOT NULL DEFAULT NOW()
) TABLESPACE DEMO_TZ;

-- LỚP HỌC
DROP TABLE IF EXISTS LOP_HOC CASCADE;
CREATE TABLE LOP_HOC (
	MA_LOP          SERIAL 			PRIMARY KEY,
	TEN_LOP         VARCHAR(200) 	NOT NULL,
	NGAY_KHAI_GIANG DATE         	NOT NULL,
	NGAY_KET_THUC   DATE         	NOT NULL CHECK (NGAY_KET_THUC >= NGAY_KHAI_GIANG),
	KHOA_HOC        INT       		NOT NULL REFERENCES KHOA_HOC(MA_KHOA_HOC),
	GV_PHU_TRACH    INT       		NOT NULL REFERENCES GIAO_VIEN(MA_GV),
	CREATED_AT      TIMESTAMPTZ  	NOT NULL DEFAULT NOW(),
	UPDATED_AT      TIMESTAMPTZ  	NOT NULL DEFAULT NOW()
) TABLESPACE DEMO_TZ;


-- ĐĂNG KÝ KHÓA HỌC
DROP TABLE IF EXISTS DANG_KY CASCADE;
CREATE TABLE DANG_KY (
	DANG_KY_ID    SERIAL 		PRIMARY KEY,
	MA_SV         INT      		NOT NULL REFERENCES HOC_VIEN(MA_SV),
	MA_KHOA_HOC   INT      		NOT NULL REFERENCES KHOA_HOC(MA_KHOA_HOC),
	NGAY_DANG_KY  DATE        	NOT NULL DEFAULT CURRENT_DATE,
	TRANG_THAI    TEXT        	NOT NULL DEFAULT 'ACTIVE' CHECK (TRANG_THAI IN ('ACTIVE','CANCELLED','COMPLETED')),
	CREATED_AT    TIMESTAMPTZ 	NOT NULL DEFAULT NOW(),
	UPDATED_AT    TIMESTAMPTZ 	NOT NULL DEFAULT NOW()
) TABLESPACE DEMO_TZ;

-- XẾP LỚP
DROP TABLE IF EXISTS XEP_LOP CASCADE;
CREATE TABLE XEP_LOP (
	XEP_LOP_ID     SERIAL 			PRIMARY KEY,
	DANG_KY_ID     INT  			NOT NULL UNIQUE REFERENCES DANG_KY(DANG_KY_ID) ON DELETE CASCADE,
	MA_LOP         INT  			NOT NULL REFERENCES LOP_HOC(MA_LOP),
	NGAY_VAO_LOP   DATE    			NOT NULL DEFAULT CURRENT_DATE,
	DIEM_CUOI_KHOA NUMERIC(5,2),
	CREATED_AT     TIMESTAMPTZ 		NOT NULL DEFAULT NOW(),
	UPDATED_AT     TIMESTAMPTZ 		NOT NULL DEFAULT NOW()
) TABLESPACE DEMO_TZ;


-- 3. Tạo ràng buộc cho nghiệp vụ cụ thể sau:
-- Đảm bảo mỗi học viên chỉ được đăng ký một lần duy nhất vào một lớp học cụ thể
CREATE UNIQUE INDEX UQ_HV_LOP_ONCE 
ON XEP_LOP (MA_LOP, (SELECT MA_SV FROM DANG_KY DK WHERE DK.DANG_KY_ID = XEP_LOP.DANG_KY_ID))
TABLESPACE DEMO_TZ;

-- Đảm bảo mỗi học viên chỉ có một đăng ký hợp lệ cho một khóa học
CREATE UNIQUE INDEX UQ_DK_SV_KHOA_ACTIVE
ON DANG_KY (MA_SV, MA_KHOA_HOC)
TABLESPACE DEMO_TZ;


-- 4. Tạo index để tối ưu truy vấn cho các nghiệp vụ sau:
-- Tìm kiếm tất cả các lớp thuộc một khóa học cụ thể
EXPLAIN ANALYZE
SELECT * FROM LOP_HOC
WHERE KHOA_HOC = 1;


