-- Câu 1
-- Lấy tất cả các cột từ bảng customer.
SELECT * FROM CUSTOMER;

-- Câu 2
-- Lấy tên và email của tất cả khách hàng.
SELECT CUSTOMER_NAME, EMAIL FROM CUSTOMER;

-- Câu 3
-- Lấy 10 khách hàng đầu tiên.
SELECT CUSTOMER_ID, CUSTOMER_NAME FROM CUSTOMER
LIMIT 10;

-- Câu 4
-- Lấy danh sách đơn hàng gồm id, order_number, total_amount.
SELECT ID, ORDER_NUMBER, TOTAL_AMOUNT FROM ORDERS;

-- Câu 5
-- Lấy các khách hàng ở thành phố “New York”.
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY FROM CUSTOMER
WHERE CITY = 'New York';

-- Câu 6
-- Tìm các khách hàng có vip_tier = 'GOLD'.
SELECT CUSTOMER_ID, CUSTOMER_NAME, VIP_TIER FROM CUSTOMER
WHERE VIP_TIER = 'GOLD';

-- Câu 7
-- Tìm khách hàng có loyalty_points > 2000.
SELECT CUSTOMER_ID, CUSTOMER_NAME, LOYALTY_POINTS FROM CUSTOMER
WHERE LOYALTY_POINTS > 2000;

-- Câu 8
-- Tìm khách hàng có tên bắt đầu bằng 'James'.
SELECT CUSTOMER_ID, CUSTOMER_NAME FROM CUSTOMER
WHERE CUSTOMER_NAME ILIKE 'James%';

-- Câu 9
-- Tìm đơn hàng có status = 'CANCELLED'.
SELECT ORDER_NUMBER, STATUS FROM ORDERS
WHERE STATUS = 'CANCELLED';

-- Câu 10
-- Lấy 5 đơn hàng có total_amount cao nhất.
SELECT ORDER_NUMBER, TOTAL_AMOUNT FROM ORDERS
ORDER BY TOTAL_AMOUNT DESC
LIMIT 5;

-- Câu 11
-- Tìm khách hàng sinh từ 1990 đến 2000.
SELECT CUSTOMER_ID, CUSTOMER_NAME, EXTRACT(YEAR FROM BIRTH_DATE) AS BIRTH_YEAR
FROM CUSTOMER
WHERE BIRTH_DATE BETWEEN DATE '1990-01-01' AND DATE '2000-12-31';

-- Câu 12
-- Tìm đơn hàng có tổng tiền từ 100 đến 200 USD.
SELECT ORDER_NUMBER, TOTAL_AMOUNT FROM ORDERS
WHERE TOTAL_AMOUNT BETWEEN 100 AND 200;

-- Câu 13
-- Tìm khách hàng ở thành phố “Los Angeles” hoặc “Chicago”.
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY FROM CUSTOMER
WHERE CITY IN ('Los Angeles', 'Chicago');

-- Câu 14
-- Lấy đơn hàng thanh toán bằng thẻ và trạng thái = 'PAID'.
SELECT ORDER_NUMBER, PAYMENT_METHOD, STATUS FROM ORDERS
WHERE PAYMENT_METHOD = 'CARD' AND STATUS = 'PAID';

-- Câu 15
-- Lấy khách hàng có email kết thúc bằng gmail.com.
SELECT CUSTOMER_ID, CUSTOMER_NAME, EMAIL FROM CUSTOMER
WHERE EMAIL ILIKE '%@gmail.com';

-- Câu 16
-- Tìm 10 khách hàng có nhiều loyalty_points nhất.
SELECT CUSTOMER_ID, CUSTOMER_NAME, LOYALTY_POINTS FROM CUSTOMER
ORDER BY LOYALTY_POINTS DESC
LIMIT 10;

-- Câu 17
-- Lấy 5 đơn hàng gần nhất theo created_at.
SELECT ORDER_NUMBER, CREATED_AT FROM ORDERS
ORDER BY CREATED_AT DESC
LIMIT 5;

-- Câu 18
-- Tìm khách hàng mới đăng ký gần đây nhất.
SELECT CUSTOMER_ID, CUSTOMER_NAME, CREATED_AT FROM CUSTOMER
ORDER BY CREATED_AT DESC
LIMIT 1;

-- Câu 19
-- Lấy 10 khách hàng sinh sớm nhất (tuổi lớn nhất).
SELECT CUSTOMER_ID, CUSTOMER_NAME, AGE(CURRENT_DATE, BIRTH_DATE)
FROM CUSTOMER
ORDER BY BIRTH_DATE
LIMIT 10;

-- Câu 20
-- Lấy 5 đơn hàng có phí vận chuyển cao nhất.
SELECT ORDER_NUMBER, SHIPPING_FEE FROM ORDERS
ORDER BY SHIPPING_FEE DESC
LIMIT 5;

-- Câu 21
-- Lấy 10 khách hàng nữ có loyalty_points cao nhất.
SELECT CUSTOMER_ID, CUSTOMER_NAME, GENDER, LOYALTY_POINTS
FROM CUSTOMER
WHERE GENDER = 'F'
ORDER BY LOYALTY_POINTS DESC
LIMIT 10;

-- Câu 22
-- Tìm 5 đơn hàng lớn nhất nhưng chỉ lấy của kênh web.
SELECT ORDER_NUMBER, CHANNEL, TOTAL_AMOUNT FROM ORDERS
WHERE CHANNEL = 'web'
ORDER BY TOTAL_AMOUNT DESC
LIMIT 5;

-- Câu 23
-- Lấy 5 đơn hàng nhỏ nhất có trạng thái PAID.
SELECT ORDER_NUMBER, STATUS, TOTAL_AMOUNT FROM ORDERS
WHERE STATUS = 'PAID'
ORDER BY TOTAL_AMOUNT
LIMIT 5;

-- Câu 24
-- Lấy 10 khách hàng VIP (vip_tier khác NONE) mới nhất theo ngày tạo.
SELECT CUSTOMER_ID, CUSTOMER_NAME, VIP_TIER, CREATED_AT
FROM CUSTOMER
WHERE VIP_TIER != 'NONE'
ORDER BY CREATED_AT DESC
LIMIT 10;

-- Câu 25
-- Lấy 5 khách hàng đã opt-in marketing có nhiều loyalty_points nhất.
SELECT CUSTOMER_ID, CUSTOMER_NAME, MARKETING_OPT_IN, LOYALTY_POINTS
FROM CUSTOMER
WHERE MARKETING_OPT_IN = TRUE
ORDER BY LOYALTY_POINTS DESC
LIMIT 5;



-- Index
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_CITY ON CUSTOMER (CITY);

CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_VIP ON CUSTOMER (VIP_TIER);

CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_LOYALTY_POINTS ON CUSTOMER (LOYALTY_POINTS);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_NAME ON CUSTOMER USING GIN (CUSTOMER_NAME GIN_TRGM_OPS);

CREATE INDEX IF NOT EXISTS IDX_ORDERS_STATUS ON ORDERS (STATUS);

CREATE INDEX IF NOT EXISTS IDX_ORDERS_TOTAL_AMOUNT ON ORDERS (TOTAL_AMOUNT DESC);

CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_EMAIL ON CUSTOMER USING GIN (EMAIL GIN_TRGM_OPS);

CREATE INDEX IF NOT EXISTS IDX_ORDERS_CREATED_AT ON ORDERS (CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_CREATED_AT ON CUSTOMER (CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_ORDERS_SHIPPING_FEE ON ORDERS (SHIPPING_FEE DESC);







