-- Câu 1
-- EXPLAIN ANALYZE
SELECT
	UPPER(CUSTOMER_NAME) AS TEN_KHACH_HANG,
	LOWER(EMAIL) AS EMAIL
FROM
	CUSTOMER
LIMIT
	10;

-- Câu 2
SET ENABLE_SEQSCAN = ON;
EXPLAIN
ANALYZE
SELECT
	ID,
	ORDER_NUMBER,
	TOTAL_AMOUNT,
	TOTAL_AMOUNT * 1.1 AS TONG_SAU_THUE
FROM
	ORDERS
WHERE
	TOTAL_AMOUNT BETWEEN 100 AND 500;

-- Câu 3
EXPLAIN
ANALYZE
SELECT
	CUSTOMER_ID,
	CUSTOMER_NAME,
	VIP_TIER
FROM
	CUSTOMER
WHERE
	VIP_TIER IN ('GOLD', 'PLATINUM')
ORDER BY
	CUSTOMER_NAME
LIMIT
	1000
OFFSET
	500;

-- Câu 4
SELECT DISTINCT
	CITY
FROM
	CUSTOMER
WHERE
	VIP_TIER IN ('GOLD', 'PLATINUM')
	AND IS_ACTIVE = TRUE
ORDER BY
	CITY;

-- Câu 5
SELECT
	ID,
	ORDER_NUMBER,
	STATUS,
	CASE
		WHEN STATUS = 'PENDING' THEN 'Chờ xử lý'
		WHEN STATUS IN ('PAID', 'SHIPPED') THEN 'Đang thực hiện'
		ELSE 'Khác'
	END AS TRANG_THAI_DON_HANG
FROM
	ORDERS;

-- Câu 6
SELECT
	CUSTOMER_ID,
	CUSTOMER_NAME,
	CASE
		WHEN CUSTOMER_NAME LIKE 'Je%' THEN 'Tên bắt đầu bằng Je'
		WHEN CUSTOMER_NAME ILIKE '%smith%' THEN 'Tên có chứa Smith'
		ELSE 'Khác'
	END AS PHAN_LOAI_THEO_TEN
FROM
	CUSTOMER
LIMIT
	100;

-- Nâng cao
-- Câu 1
SELECT
	ID,
	ORDER_NUMBER,
	STATUS
FROM
	ORDERS
WHERE
	STATUS = 'DELIVERED'
LIMIT
	20
OFFSET
	20 * (3 - 1);

-- Câu 2
SELECT
	CONCAT(CUSTOMER_NAME, ' ', EMAIL, ' ', PHONE) AS FULL_INFO,
	LENGTH(CUSTOMER_NAME) AS NAME_LENGTH,
	SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1),
	CREATED_AT
FROM
	CUSTOMER
ORDER BY
	CREATED_AT DESC
LIMIT
	10;

-- Câu 3
SELECT
	ID,
	ORDER_NUMBER,
	TOTAL_AMOUNT,
	CASE
		WHEN TOTAL_AMOUNT < 50 THEN 'Rất nhỏ'
		WHEN TOTAL_AMOUNT BETWEEN 50 AND 199  THEN 'Nhỏ'
		WHEN TOTAL_AMOUNT BETWEEN 200 AND 999  THEN 'Trung bình'
		ELSE 'Lớn'
	END AS ORDER_VALUE_LEVEL,
	CREATED_AT
FROM
	ORDERS
ORDER BY
	CREATED_AT DESC
LIMIT
	100;

-- Bài tập tối ưu hóa
-- Câu 1
EXPLAIN 
ANALYZE
SELECT *
FROM ORDERS
WHERE CUSTOMER_ID = 90000;

CREATE INDEX IF NOT EXISTS IDX_ORDERS_CUSTOMER_ID ON ORDERS (CUSTOMER_ID);
-- Vì filter so sánh bành trên một cột nên sẽ sử dụng B-Tree index giúp tối ưu không cần phải duyệt toàn bộ bảng
DROP INDEX IF EXISTS IDX_ORDERS_CUSTOMER_ID;

-- Câu 2
EXPLAIN 
ANALYZE
SELECT *
FROM ORDERS
WHERE CUSTOMER_ID BETWEEN 80000 AND 99000;

DROP INDEX IF EXISTS IDX_ORDERS_CUSTOMER_ID;
-- Vì số cột cần trả về tương đối lớn, không nên sài index 
-- Dùng index sẽ tốn chi phí scan index + truy heap

-- Câu 3
EXPLAIN 
ANALYZE
SELECT *
FROM ORDERS
WHERE CUSTOMER_ID BETWEEN 90000 AND 90100;

CREATE INDEX IF NOT EXISTS IDX_ORDERS_CUSTOMER_ID ON ORDERS (CUSTOMER_ID);
-- Vì số cột cần trả về nhỏ, nên xài index
-- Do ít row -> nên ít phải truy heap -> đi thẳng tới row cần, không cần quét toàn bộ data
DROP INDEX IF EXISTS IDX_ORDERS_CUSTOMER_ID;

-- Câu 4
EXPLAIN 
ANALYZE
SELECT COUNT(*)
FROM ORDERS
WHERE STATUS = 'PAID' AND ORDER_DATE >= CURRENT_DATE - INTERVAL '30 DAYS';

CREATE INDEX IF NOT EXISTS IDX_ORDERS_STATUS_ORDER_DATE ON ORDERS (STATUS, ORDER_DATE);
DROP INDEX IF EXISTS IDX_ORDERS_STATUS_ORDER_DATE;

-- Câu 5
EXPLAIN 
ANALYZE
SELECT ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT
FROM ORDERS
WHERE STATUS = 'DELIVERED'
ORDER BY ORDER_DATE DESC, ORDER_NUMBER ASC
LIMIT 50 OFFSET 0;

CREATE INDEX IF NOT EXISTS IDX_ORDERS_STATUS_DATE_NUMBER 
ON ORDERS (STATUS, ORDER_DATE DESC, ORDER_NUMBER ASC);

-- Vì select các cột như ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT
-- Ta có thể sự dụng covering index -> include thêm 2 cột CUSTOMER_ID, TOTAL_AMOUNT
-- Khi đó sẽ không cần heap lookup để lấy 2 giá trị của 2 cột CUSTOMER_ID, TOTAL_AMOUNT

CREATE INDEX IF NOT EXISTS IDX_ORDERS_STATUS_DATE_NUMBER 
ON ORDERS (STATUS, ORDER_DATE DESC, ORDER_NUMBER ASC)
INCLUDE (CUSTOMER_ID, TOTAL_AMOUNT);
DROP INDEX IF EXISTS IDX_ORDERS_STATUS_DATE_NUMBER;

-- Câu 6
EXPLAIN 
ANALYZE
SELECT ORDER_NUMBER
FROM ORDERS
WHERE DATE_TRUNC('DAY', ORDER_DATE) = DATE '2025-08-01';

-- Tạo index trên order_date để không phải duyệt toàn bộ mảng
CREATE INDEX IF NOT EXISTS IDX_ORDERS_ORDER_DATE ON ORDERS (ORDER_DATE);
DROP INDEX IF EXISTS IDX_ORDERS_STATUS_DATE_NUMBER;

-- Loại bỏ function trong filter để có thể sử dụng index
EXPLAIN 
ANALYZE
SELECT ORDER_NUMBER
FROM ORDERS
WHERE order_date >= TIMESTAMP '2025-08-01 00:00:00'
  AND order_date < TIMESTAMP '2025-08-02 00:00:00';






