-- BÀI TẬP CƠ BẢN
-- CÂU 1
SELECT STATUS, SUM(TOTAL_AMOUNT) AS TOTAL_SALES
FROM ORDERS
GROUP BY STATUS
ORDER BY TOTAL_SALES DESC;

-- CÂU 2
SELECT PAYMENT_METHOD, COUNT(*) AS SO_DON_HANG
FROM ORDERS
GROUP BY PAYMENT_METHOD
ORDER BY SO_DON_HANG DESC;

-- CÂU 3
SELECT 
    DATE_TRUNC('MONTH', ORDER_DATE) AS THANG,
    COUNT(*) AS SO_DON_HANG,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES,
    ROUND(AVG(TOTAL_AMOUNT), 2) AS AVG_SALES
FROM ORDERS
WHERE EXTRACT(YEAR FROM ORDER_DATE) = 2025
GROUP BY DATE_TRUNC('MONTH', ORDER_DATE)
ORDER BY THANG;

-- CÂU 4
SELECT
	SIGNUP_SOURCE,
	COUNT(*) AS TONG_KHACH,
	COUNT(*) FILTER (WHERE MARKETING_OPT_IN = TRUE) AS SO_KHACH_OPT_IN,
	ROUND(
        100.0 * COUNT(*) FILTER (WHERE MARKETING_OPT_IN = TRUE) / COUNT(*),
        2
    ) AS PHAN_TRAM_OPT_IN,
	BOOL_OR(MARKETING_OPT_IN) AS ANY_OPT_IN,
	BOOL_AND(MARKETING_OPT_IN) AS ALL_OPT_IN
FROM CUSTOMER
GROUP BY SIGNUP_SOURCE;

-- CÂU 5
SELECT
	SHIPPING_METHOD,
	ROUND(AVG(SHIPPING_FEE), 2)
FROM ORDERS
GROUP BY SHIPPING_METHOD
HAVING AVG(SHIPPING_FEE) > 5

-- Bài tập nâng cao
-- Câu 1
SELECT 
	ORDER_DATE,
	SUM(TOTAL_AMOUNT) AS TOTAL_SALES,
	COUNT(*) AS SO_DON_HANG
FROM ORDERS
GROUP BY ORDER_DATE
HAVING COUNT(*) >= 10000
ORDER BY TOTAL_SALES DESC
LIMIT 10;

-- Câu 2
SELECT 
	SHIPPING_METHOD,
	COUNT(*) AS SO_DON_HANG,
	COUNT(*) FILTER (WHERE COUPON_CODE IS NOT NULL) AS SO_DON_DUNG_COUPON,
	ROUND(100.0 * COUNT(*) FILTER (WHERE COUPON_CODE IS NOT NULL) / COUNT(*), 2) AS TY_LE_SU_DUNG
FROM ORDERS
GROUP BY SHIPPING_METHOD;

-- Câu 3
SELECT
	CITY,
	ARRAY_TO_STRING((ARRAY_AGG(CUSTOMER_NAME ORDER BY CREATED_AT DESC)) [1:5], ', ') AS FIVE_CUSTOMER_NAME,
	COUNT(*) AS SO_KHACH_HANG
FROM CUSTOMER
WHERE IS_ACTIVE = TRUE AND VIP_TIER IN ('GOLD', 'PLATINUM')
GROUP BY CITY
ORDER BY SO_KHACH_HANG DESC
LIMIT 10;

