-- BÀI TẬP CƠ BẢN
-- Câu 1
-- Lấy đơn hàng mới nhất cho từng khách hàng (chỉ lấy 10 khách hàng đầu)
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME,
	(
		SELECT ORDER_NUMBER
		FROM ORDERS O
		WHERE C.CUSTOMER_ID = O.CUSTOMER_ID
		ORDER BY ORDER_DATE DESC
		LIMIT 1
	) LASTEST_ORDER
FROM CUSTOMER C
LIMIT 10;

-- Câu 2.1
-- Lấy tất cả đơn hàng của những khách hàng VIP (GOLD hoặc PLATINUM).
SELECT
	O.CUSTOMER_ID,
	O.ORDER_NUMBER
FROM ORDERS O
WHERE O.CUSTOMER_ID IN (
	SELECT
		C.CUSTOMER_ID
	FROM CUSTOMER C
	WHERE C.VIP_TIER IN ('GOLD', 'PLATINUM')
);

-- Câu 2.2
-- Tìm khách hàng có ít nhất một đơn hàng bị hủy.
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME
FROM CUSTOMER C
WHERE EXISTS (
	SELECT 1
	FROM ORDERS O
	WHERE C.CUSTOMER_ID = O.CUSTOMER_ID AND STATUS = 'CANCELLED'
);

-- Câu 2.3
-- Tìm 10 khách hàng đầu tiên có tổng chi tiêu > 30000
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
FROM CUSTOMER C
WHERE (
    SELECT SUM(O.TOTAL_AMOUNT)
    FROM ORDERS O
    WHERE O.CUSTOMER_ID = C.CUSTOMER_ID
) > 30000
LIMIT 10;

-- Câu 3.1
-- Tìm ngày nào có nhiều đơn hàng nhất
SELECT *
FROM (
	SELECT
		DATE_TRUNC('DAY', ORDER_DATE) AS DATE,
		COUNT(*) AS SO_DON_HANG
	FROM ORDERS
	GROUP BY DATE_TRUNC('DAY', ORDER_DATE)
	ORDER BY SO_DON_HANG DESC
)
LIMIT 1;

-- Câu 3.2
-- Tính tỷ lệ đơn hàng theo trạng thái
SELECT
	T.STATUS,
	T.SO_DON_HANG, 
	TOTAL.TONG,
	ROUND(100.0 * T.SO_DON_HANG / TOTAL.TONG, 5) AS TY_LE	
FROM (
	SELECT
		STATUS,
		COUNT(*) AS SO_DON_HANG
	FROM ORDERS
	GROUP BY STATUS
) AS T, 
(
	SELECT COUNT(*) AS tong FROM orders
) TOTAL

-- Bài tập mở rộng
-- Câu 1
-- Tìm khách hàng có ít nhất một đơn CANCELLED và có ít nhất một đơn DELIVERED
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME
FROM CUSTOMER C
WHERE EXISTS (
	SELECT 1
	FROM ORDERS O
	WHERE C.CUSTOMER_ID = O.CUSTOMER_ID AND STATUS = 'CANCELLED'
) AND EXISTS (
	SELECT 1
	FROM ORDERS O
	WHERE C.CUSTOMER_ID = O.CUSTOMER_ID AND STATUS = 'DELIVERED'
);

-- Câu 2
-- Tìm ngày có tổng doanh thu cao nhất trong toàn bộ bảng orders
SELECT *
FROM (
	SELECT
		DATE_TRUNC('DAY', ORDER_DATE) AS DATE,
		SUM(TOTAL_AMOUNT) AS TONG_DOANH_THU
	FROM ORDERS
	GROUP BY DATE_TRUNC('DAY', ORDER_DATE)
	ORDER BY TONG_DOANH_THU DESC
)
LIMIT 1;

-- Bài nâng cao buổi 3
EXPLAIN ANALYZE
SELECT
	DATE_TRUNC('DAY', ORDER_DATE) AS DATE,
	SUM(TOTAL_AMOUNT) AS TONG_DOANH_THU
FROM ORDERS
GROUP BY DATE_TRUNC('DAY', ORDER_DATE)
ORDER BY DATE DESC
LIMIT 30;

CREATE MATERIALIZED VIEW MV_DAILY_SALES AS
SELECT
	DATE_TRUNC('DAY', ORDER_DATE) AS DATE,
	SUM(TOTAL_AMOUNT) AS TONG_DOANH_THU
FROM ORDERS
GROUP BY DATE_TRUNC('DAY', ORDER_DATE)
ORDER BY DATE DESC
WITH NO DATA;

REFRESH MATERIALIZED VIEW MV_DAILY_SALES;

EXPLAIN ANALYZE
SELECT *
FROM MV_DAILY_SALES
LIMIT 30;

-- Bài nâng cao buổi 4
-- Câu 1
-- Tìm tất cả khách hàng mà tồn tại ít nhất một đơn hàng có status CANCELLED
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME
FROM CUSTOMER C
WHERE EXISTS (
	SELECT 1
	FROM ORDERS O
	WHERE C.CUSTOMER_ID = O.CUSTOMER_ID AND STATUS = 'CANCELLED'
);

-- Câu 2
-- Tìm tất cả khách hàng mà không tồn tại bất kỳ một đơn hàng có status DELIVERED
SELECT
	C.CUSTOMER_ID,
	C.CUSTOMER_NAME
FROM CUSTOMER C
WHERE NOT EXISTS (
	SELECT 1
	FROM ORDERS O
	WHERE C.CUSTOMER_ID = O.CUSTOMER_ID AND STATUS = 'DELIVERED'
);

-- Câu 3
-- Tìm khách hàng GOLD có loyalty_points lớn hơn tất cả khác PLATINUM
SELECT 
	CUSTOMER_ID,
	CUSTOMER_NAME,
	LOYALTY_POINTS
FROM CUSTOMER C
WHERE VIP_TIER = 'GOLD' AND LOYALTY_POINTS > ALL (
	SELECT 
		LOYALTY_POINTS
	FROM CUSTOMER 
	WHERE VIP_TIER = 'PLATINUM'
)

-- Câu 4
-- Tìm khách hàng SILVER có loyalty_points >= ít nhất một khách GOLD
SELECT 
	CUSTOMER_ID,
	CUSTOMER_NAME,
	LOYALTY_POINTS
FROM CUSTOMER C
WHERE VIP_TIER = 'SILVER' AND LOYALTY_POINTS >= ANY (
	SELECT 
		LOYALTY_POINTS
	FROM CUSTOMER 
	WHERE VIP_TIER = 'GOLD'
)

